/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    /** サーバーの状態を返します。 */
    get: operations["openapitutorial.controller.health.call"];
  };
}

export interface components {
  schemas: {
    /** @description サーバーの状態のレスポンス */
    get_health_response: {
      /** @enum {string} */
      status: "ok";
    };
  };
}

export interface operations {
  /** サーバーの状態を返します。 */
  "openapitutorial.controller.health.call": {
    responses: {
      /** サーバーは正常に動作しています */
      200: {
        content: {
          "application/json": components["schemas"]["get_health_response"];
        };
      };
    };
  };
}

export interface external {}
